student_count = 11

puts "The students of Villains Academy"
puts "------------------"
puts "Dr. Hanibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Normal Bates"
puts "Overall, we have #{student_count} great students."
